import Footer from "./components/main/footer";
import Header from "./components/main/header";
import { NextAuthProvider } from './Providers'
import { Analytics } from '@vercel/analytics/react';
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Menu | Lagham Restaurant",
  description: "Generated by Rockai Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-bgColor font-mainFont flex flex-col justify-start items-center relative text-textColor">
        <NextAuthProvider>
          <Header />
          {children}
          <Footer />
        </NextAuthProvider>
        <Script src="Js/main.js" />
        <Analytics />
      </body>
    </html>
  );
}
