import Image from 'next/image';
import React from 'react'
import AddToCart from '../components/item/AddToCart';

const getItem = async (id) => {
  const apiUrl = process.env.API_URL;

  try {
    const res = await fetch(`${apiUrl}/api/items/${id}`, {
      cache: 'no-store'
    })

    if (!res.ok) {
      throw new Error('Cannot Fetch The Item')
    }

    return res.json()
  } catch (error) {
    console.log(error);
  }
}

const getItems = async () => {
  const apiUrl = process.env.API_URL;
  try {
    const res = await fetch(`${apiUrl}/api/items`, {
      cache: 'no-store'
    })
    if (!res.ok) {
      throw new Error('Cannot Fetch The Items')
    }

    return res.json()
  } catch (err) {
    console.log(err);
  }
}

export async function generateMetadata({ params }) {
  const { itemid } = params
  const { item } = await getItem(itemid)
  const { titleEn, image, description } = item

  return {
    title: `${titleEn} | Warta Restaurant`,
    description: `${description} | لغم اجمد مطعم سماش برجر وفراخ في اسكندرية ❤️ | Generated by Rockai Dev`,
    siteName: 'Warta.eg',
    images: [
      {
        url: image, // Must be an absolute URL
        width: 800,
        height: 600,
      },
    ]
  }
}


export default async function Item({ params }) {
  const { itemid } = params
  const { item } = await getItem(itemid)
  const { titleEn, titleAr, category, image, price, description, points, rate } = item
  const { items } = await getItems()

  const Extras = items.filter(item => {
    const extras = item.category === 'extras'

    return extras
  })

  console.log(Extras);

  return (
    <section>
      <div className="itemInfo w-full flex flex-wrap justify-around items-center my-9">
        <div className="image">
          <Image className='rounded-xl' src={image} width={400} height={400} alt={titleAr} />
        </div>
        <div className="info flex flex-col justify-between">
          <div className="main mb-12 relative">
            <div className="title text-2xl font-bold">
              <h2 className='text-left'>{titleEn}</h2>
              <h2 className=' text-right'>{titleAr}</h2>
            </div>
            <div className="price text-3xl font-bold text-green-400 absolute top-0 right-0">
              <h4>{price} EGP</h4>
            </div>
            <div className="description">
              <p className='text-right text-xl'>{description}</p>
            </div>
          </div>
          <AddToCart itemInfo={item} ExtrasItems={Extras} />
        </div>
      </div>
      <a href="/" className='link'>Menu</a>
    </section>
  )
}
